<?xml version="1.0" encoding="utf-8"?><Database Name="hoanghiep" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TRADAKEOLAC;Initial Catalog=hoanghiep;Persist Security Info=True;User ID=sa" SettingsObjectName="Database.Properties.Settings" SettingsPropertyName="hoanghiepConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAdv" Member="tblAdvs">
    <Type Name="tblAdv">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Alias" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Statust" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblCategory_tblNew" Member="tblNews" ThisKey="Id" OtherKey="CateID" Type="tblNew" />
      <Association Name="tblUser_tblCategory" Member="tblUser" ThisKey="UserCreate" OtherKey="ID" Type="tblUser" IsForeignKey="true" />
      <Association Name="tblClass_tblCategory" Member="tblClass" ThisKey="ClassId" OtherKey="Id" Type="tblClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblComment" Member="tblComments">
    <Type Name="tblComment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Content_Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Statust" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblUser_tblComment" Member="tblUser" ThisKey="UserID" OtherKey="ID" Type="tblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblConfig" Member="tblConfigs">
    <Type Name="tblConfig">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Logo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblFile" Member="tblFiles">
    <Type Name="tblFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblNew_tblFile" Member="tblNew" ThisKey="NewsId" OtherKey="Id" Type="tblNew" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblNews" Member="tblNews">
    <Type Name="tblNew">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CateID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LinkYoutube" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Statust" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblNew_tblFile" Member="tblFiles" ThisKey="Id" OtherKey="NewsId" Type="tblFile" />
      <Association Name="tblCategory_tblNew" Member="tblCategory" ThisKey="CateID" OtherKey="Id" Type="tblCategory" IsForeignKey="true" />
      <Association Name="tblUser_tblNew" Member="tblUser" ThisKey="UserId" OtherKey="ID" Type="tblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Avata" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="IPLastLogin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblUser_tblCategory" Member="tblCategories" ThisKey="ID" OtherKey="UserCreate" Type="tblCategory" />
      <Association Name="tblUser_tblComment" Member="tblComments" ThisKey="ID" OtherKey="UserID" Type="tblComment" />
      <Association Name="tblUser_tblNew" Member="tblNews" ThisKey="ID" OtherKey="UserId" Type="tblNew" />
    </Type>
  </Table>
  <Table Name="dbo.tblClass" Member="tblClasses">
    <Type Name="tblClass">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Avata" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblClass_tblCategory" Member="tblCategories" ThisKey="Id" OtherKey="ClassId" Type="tblCategory" />
    </Type>
  </Table>
</Database>